# Generated by Django 3.0.4 on 2020-03-05 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_quiztaker_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiztaker',
            name='user',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
